### ISSUE TITLE
你好，关于转ts interfaces有些事情想要讨论下

### ISSUE THREAD

**Issue by bojun1995** [ChpShy/json2ts#2]
你好，我在我的项目https://github.com/bojun1995/o-json-crx 中使用到了您的插件

在使用过程中，我发现例如：
```
[
 {
   a: { val0: 0, val1: 1 }
 },
 {
    a: { val0: 0 }
 }
]
```

这样的同名，但是不同返回值的object会生成多个type，但是感觉这样比较合理一些
```
interface a {
  val0: number
  val1?: number
}
```

希望能和您讨论一下

**Comment by ChpShy** [comment]
emmm... 这么说也有道理。我暂时还不确定实现的复杂度，因为数组的场景还是太多了。我晚上看下～

**Comment by ChpShy** [comment]
一层结构的倒是实现了。比如
```javascript
[
   {
       a: 1, b: 2
   },
   {
       a: 1
   }
]
```

但是对象内再嵌套的结构有点太复杂了。暂时我也没什么好的方案

**Comment by bojun1995** [comment]
我感觉也是 嵌套的话复杂度太高了

**Comment by ChpShy** [comment]
已发布`v0.1.2`。支持单层嵌套。
多层嵌套等我有时间好好整理下哈哈。
